name: Linting

# When push or pull request on main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      # Note: uses: (Selects an action)
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          
      # Installing Linters
      # Note: "ESLint and Prettier must be in `package.json`"
      - name: Install Node.js dependencies
        run: npm ci

      # All linters are disabled by default
      # eslint & prettier: Javascript
      # prettier: html
      # stylelint: CSS
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
          stylelint: true
       



